apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodic-dumper
  namespace: project
spec:
  schedule: '1 2 * * *' #  1 2 * once a day at 2:01
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gcs-api-service-account
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: 'true'
          containers:
            - name: dumper
              image: thomastoumasu/k8s-mongo-dumper:3.10-amd
              env:
                - name: MONGO_URI
                  value: 'mongodb://the_username:the_password@mongo-svc.production:27017/the_database'
                - name: BUCKET
                  value: 'thomastoumasu_k8s-bucket'
              imagePullPolicy: IfNotPresent
          restartPolicy: Never # run it only once
