FROM node:alpine AS build-stage 
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY --chown=node:node package* ./
RUN npm ci --omit=dev 
COPY --chown=node:node . .
# ENV VITE_BACKEND_URL=http://localhost:8081/api/todos # for k3s, see cluster creation in create_k3scl
# ENV VITE_BACKEND_URL=http://34.88.70.145/api/todos # for gke: IP allocated by gke to its gateway or ingress
# ENV VITE_BACKEND_URL=http://www.thomastoumasu.dpdns.org/api/todos # for gke, deployment on main
ENV VITE_BACKEND_URL=http://www.thomastoumasu.xx.kg/api/todos
RUN npm run build
USER node

FROM nginx:1.25-alpine
# using default port 80 and /usr/share/nginx/html for nginx so no nginx.conf necessary
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
# no need for CMD, nginx starts up on its own
